Site Accessibility
CrackedYoda/MyPortfolio pull request #7
Opened 2023-06-13 15:56 UTC by CrackedYoda

### A report on site Accessibility
In this review we checked the following 

- Page Titles - Changes made to title name
https://github.com/CrackedYoda/MyPortfolio/blob/6bd59b70ea06002e01db3ad0193d0c20b1966cb2/index.html#L14

- Image text alternatives - Add image text alternatives
https://github.com/CrackedYoda/MyPortfolio/blob/6bd59b70ea06002e01db3ad0193d0c20b1966cb2/index.html#L121-L125

- Text headings - Replaced main heading tag to H1
https://github.com/CrackedYoda/MyPortfolio/blob/6bd59b70ea06002e01db3ad0193d0c20b1966cb2/index.html#L32-L35C16

- Color contrast -  No issues found
- Resize - No issues found
- Interaction -  No issues found
- Moving Contents -  No issues found
- Multimedia -  No issues found

2023-06-13 16:03 UTC, amon-cofie requested changes
Hi guys, 👋 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors. Please fix these linter errors and resubmit for another review. Please ensure you have a professional readme file when you submit it for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-14 08:15 UTC, CrackedYoda commented
you didn't check the linter error
the linter error is general and you marked my code invalid

2023-06-14 08:22 UTC, MargaretTechworld commented
Web hin error is general

2023-06-14 08:56 UTC, wayungi requested changes
Hi @CrackedYoda , 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] All checks performed ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Your logo has failed the contrast. This means that certain user audiences may not be able to view the logo. Kindly change the color of the logo and run the contrast test to make sure it is passing.
![contrast](https://github.com/CrackedYoda/MyPortfolio/assets/99656687/8cfcbe78-b617-41a9-8db3-b4fddea6b77f)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 08:56 UTC, wayungi commented on index.html
> +          </h1>
- [ ] Please note that the headings should be in hierarchy. You should not have an `h1` below an `h3` as show below. The problem is cause by the **Logo** which you made a heading instead of an anchor tag. Please fix this.

**Your current heading hierarchy is a below**
![h](https://github.com/CrackedYoda/MyPortfolio/assets/99656687/5d1518d1-43d4-4e7f-b96d-437b12d028ee)

2023-06-14 14:01 UTC, closed without merging

2023-06-14 14:02 UTC, frank1738 reviewed
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project with failing `stylelint` checks. Kindly fix them and resubmit your project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**